#!/usr/bin/env python
import sys, os, urllib, stat, json
from datetime import date
import findfilesconf as conf

def read_files(param):
	os.putenv('KEYWORD', param)
	lines = os.popen('locate -d {0} -ib "$KEYWORD"'.format(conf.DB_FILE)).readlines()
	if not conf.DEDICATED_DB_FILE:
		lines = filter(lambda s: s.startswith(conf.BASE_DIR), lines)
	res = []
	count = len(lines)
	i = 0
	while (len(res) < conf.LIMIT) and (i < len(lines)):
		name = lines[i][:-1]
		try:
			st = os.stat(name)
			res.append({'name': name[len(conf.BASE_DIR):], 'isdir': stat.S_ISDIR(st.st_mode), 'size': st.st_size, 'date': date.fromtimestamp(st.st_mtime).strftime(conf.TIME_STYLE)})
		except Exception:
			count -= 1
		i += 1
	return { 'base': conf.BASE_URL, 'count': count, 'list': res }

def response(obj):
	print 'Content-type: text/plain; charset=utf-8'
	print ''
	print json.dumps(obj, ensure_ascii=False)
	
param = urllib.unquote(os.getenv('QUERY_STRING')).strip()
if len(param) < 2:
	response({ 'error': 'please use a longer keyword' })
else:
	response(read_files(param))

