#!/usr/bin/env python
import sys
import os
import urllib

param = urllib.unquote(os.getenv('QUERY_STRING')).strip()

print 'Content-type: text/plain; charset=utf-8'
print ''
if len(param) < 2:
	print 'Error: please use a longer keyword'
	sys.exit()
sys.stdout.flush()
os.putenv('KEYWORD', param)
os.system('bash ./findall.sh')

